# ==========================================
# LAYER: APP (Frontend)
# SERVICE: Client (React + Vite)
# ==========================================

networks: { riffle_network: { external: true } }
services:
  client:
    build:
      context: ../../apps/client
      dockerfile: Dockerfile
      target: ${DOCKER_STAGE:-dev}
    container_name: riffle-client
    ports: ["5173:5173"] # Waf blocks port 80
    environment: { VITE_API_URL: http://localhost:1968 }
    networks: [riffle_network]
