# ==========================================
# LAYER: DEVTOOLS (Development Only)
# SERVICE: MailHog (SMTP), HttpBin, Redis Commander
# ==========================================

networks: { riffle_network: { external: true } }
services:
  httpbin:
    image: kennethreitz/httpbin
    container_name: dev-httpbin
    ports: ["8082:80"]
    networks: [riffle_network]
  mailhog:
    image: mailhog/mailhog
    container_name: dev-mailhog
    ports: ["1025:1025", "8025:8025"]
    networks: [riffle_network]
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: dev-redis-commander
    environment:
      - REDIS_HOSTS=game:active-game-redis:6379
    ports: ["8081:8081"]
    networks: [riffle_network]
    depends_on: [active-game-redis]
