# ==========================================
# LAYER: DATA (Active)
# SERVICE: Redis (Hot Data, Sessions)
# ==========================================

services:
  active-game-redis:
    image: redis:7-alpine
    container_name: active-game-redis
    command: ${REDIS_START_CMD}
    ports:
      - "${GAME_REDIS_PORT}:6379"
    volumes:
      - compose_game_redis_data:/data
      - ../config/redis/users.acl:/etc/redis/users.acl
      # Always read-only mount for certificates even if on dev environment is empty
      - ../secrets/certs:/certs:ro
    networks:
      - riffle_network

volumes:
  compose_game_redis_data: