# ==========================================
# LAYER: EDGE
# SERVICE: API Gateway (Kong) + Cache
# ==========================================

networks: { riffle_network: { external: true } }
services:
  kong-redis:
    image: redis:alpine
    container_name: cache-kong-redis
    networks: [riffle_network]
  
  kong-migrations:
    image: kong:latest
    container_name: infra-kong-migrations
    command: kong migrations bootstrap
    depends_on:
      kong-database:
        condition: service_healthy
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: store-kong-pg
      KONG_PG_USER: ${KONG_PG_USER}
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD}
    networks: [riffle_network]

  kong:
    image: kong:latest # OSS
    container_name: infra-kong
    depends_on:
      kong-redis:
        condition: service_started
      kong-migrations:
        condition: service_completed_successfully
    environment:
      # --- DATABASE ---
      KONG_DATABASE: postgres
      KONG_PG_HOST: store-kong-pg
      KONG_PG_USER: ${KONG_PG_USER}
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD}
      
      # --- LISTENS ---
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_LISTEN: 0.0.0.0:8002 # Manager
      KONG_STATUS_LISTEN: 0.0.0.0:8100    # Prometheus Metrics

      # --- GUI ---
      KONG_ADMIN_GUI_URL: http://localhost:8002
      
      # --- PLUGINS & FEATURES ---
      KONG_PLUGINS: bundled,prometheus
      KONG_WASM: on 
      
      # --- TUNING ---
      KONG_MEM_CACHE_SIZE: 128m
      KONG_NGINX_WORKER_PROCESSES: ${KONG_WORKERS:-1}
      KONG_NGINX_PROXY_LARGE_CLIENT_HEADER_BUFFERS: "8 24k" # Header overflow
      
    ports:
      - "8000:8000" # Proxy
      - "8001:8001" # Admin API
      - "8002:8002" # Manager GUI
      - "8100:8100" # Metrics Endpoint
    networks: [riffle_network]