# ==========================================
# LAYER: SERVICE (Microservice)
# SERVICE: Music Service (Spotify/Deezer Integration)
# ==========================================

networks: { riffle_network: { external: true } }
services:
  music-service:
    build:
      context: ../../apps/music-service
      dockerfile: Dockerfile
      target: ${DOCKER_STAGE:-dev}
    container_name: service-music
    environment:
      MTLS_ENABLED: ${MTLS_ENABLED}
      MTLS_CA_PATH: ${MTLS_CA_PATH}
      MTLS_CERT_PATH: ${MTLS_CERT_PATH}
      MTLS_KEY_PATH: ${MTLS_KEY_PATH}
    networks: [riffle_network]