# ==========================================
# LAYER: SERVICE
# SERVICE: Core API (Auth & Orchestration)
# ==========================================

networks: { riffle_network: { external: true } }
services:
  core-api:
    build:
      context: ../../apps/core-api
      dockerfile: Dockerfile
      target: ${DOCKER_STAGE:-dev}
    image: node:22-alpine # Temp image, will be replaced by build
    container_name: service-core-api
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      
      # --- DATABASE ---
      PGHOST: store-game-pg
      PGPORT: 5432
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGDATABASE: ${POSTGRES_DB}
      
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@store-game-pg:5432/${POSTGRES_DB}

      # --- SECURITY ---
      MTLS_ENABLED: ${MTLS_ENABLED}
      MTLS_CA_PATH: ${MTLS_CA_PATH}
      MTLS_CERT_PATH: ${MTLS_CERT_PATH}
      MTLS_KEY_PATH: ${MTLS_KEY_PATH}
      
      # --- OTHERS ---
      REDIS_HOST: active-game-redis
      JWT_SECRET: ${JWT_SECRET}
      
    volumes:
      - ../secrets/certs:/app/certs:ro
    ports: ["${PORT}:${PORT}"]
    networks: [riffle_network]