# ==========================================
# LAYER: SERVICE (Async)
# SERVICE: Worker (Redis to Postgres Sync)
# ==========================================

networks: { riffle_network: { external: true } }
services:
  db-sync-worker:
    build:
      context: ../../apps/worker
      dockerfile: Dockerfile
      target: ${DOCKER_STAGE:-dev}
    container_name: service-worker
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@store-game-pg:5432/${POSTGRES_DB}
      MTLS_ENABLED: ${MTLS_ENABLED}
      MTLS_CA_PATH: ${MTLS_CA_PATH}
      MTLS_CERT_PATH: ${MTLS_CERT_PATH}
      MTLS_KEY_PATH: ${MTLS_KEY_PATH}
      REDIS_HOST: active-game-redis
    volumes:
      - ../secrets/certs:/app/certs:ro
    networks: [riffle_network]