# ==========================================
# LAYER: SERVICE (Engine)
# SERVICE: Matchmaker (Go - High Performance)
# ==========================================

networks: { riffle_network: { external: true } }
services:
  matchmaker:
    build:
      context: ../../apps/game-engine
      dockerfile: Dockerfile
      target: ${DOCKER_STAGE:-dev}
    container_name: service-matchmaker
    environment: 
      REDIS_HOST: active-game-redis
      MTLS_ENABLED: ${MTLS_ENABLED}
      MTLS_CA_PATH: ${MTLS_CA_PATH}
      MTLS_CERT_PATH: ${MTLS_CERT_PATH}
      MTLS_KEY_PATH: ${MTLS_KEY_PATH}
    volumes:
      - ../secrets/certs:/app/certs:ro
    networks: [riffle_network]