FROM golang:1.21-alpine AS base
WORKDIR /app

# --- DEV & TEST ---
FROM base AS dev
CMD ["sh", "-c", "echo 'Music Service (DEV) started...' && tail -f /dev/null"]

# Dev = Test
FROM dev AS test

# --- PROD & STAGE ---
FROM base AS prod
CMD ["sh", "-c", "echo 'Music Service (PROD) started...' && tail -f /dev/null"]

# Stage = Prod
FROM prod AS stage